Encoding:
  Enabled: false

LineLength:
  Max: 200

IfUnlessModifier:
  Enabled: false

MethodLength:
  Max: 15

TrivialAccessors:
  ExactNameMatch: true

SpaceBeforeFirstArg:
  Enabled: false

# no longer required
# NumericLiteralPrefix:
#  EnforcedOctalStyle: zero_only
